### PR TITLE
Merging Django CI and build a docker container, publish and deploy it to Tencent Kubernetes Engine 

### PR DESCRIPTION
**Pull request by Watemlifts**
Two files have been added to merge as one. The action in the merging is to Upload a Build Artifact and give it a time to expire unless changed in the setting and then Setup, Build, Publish, and Deploy it to Tencent Kubernetes Engine. This is an improvement in the workflow and final deployment.

### CODE REVIEW

**Comment by Watemlifts** [comment]
No access to secrets by maintainers

**Comment by Watemlifts** [comment]
The two files have been changed and reviewed.

**Comment by redianmarku** [comment]
I think you made pull request to wrong repository.

**Comment by Watemlifts** [comment]
Merge possible

**Pull request closed without merging**
